services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ORDER_API_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_API_DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ORDER_API_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ORDER_API_PGADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ORDER_API_GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ORDER_API_GRAFANA_PASS}

  order-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ORDER_API_DB_USER=${ORDER_API_DB_USER}
      - ORDER_API_DB_PASS=${ORDER_API_DB_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin
      - grafana
      - prometheus

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:
  prometheus_data:

networks:
  default:
    external:
      name: my_network

